server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/pretonik/config-repo
         basedir: target/config
security:
   user:
      password: password
